
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.rag
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml

hengnao:
  appKey: hengnaoj9yvrMgfcM5uc0CTat76
  appSecret: tmebar6bqvbixn3u8xwu4q58z7opu0ko

qwen:
  apiKey: sk-47912a5b978c442c8b21e8c6a41324d4
  textEmbedding: text-embedding-v3
  textDimensions: 1024


netty:
  # 服务器的TCP端口，默认为8080
  port: 8009
  sport: 8010
  host: 127.0.0.1 #客户端用到

spring:
  redis:
    host: 192.168.31.76
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456



milvus:
  host: 192.168.31.94
  port: 19530
  collection: embedding_collection
  partition: one

aliyun:
  market:
    appkey: 204625460
    appsecret: dY8ZGImgSKSaaU4jaDE9dambUXYDNFHK
    appcode: be492ba3a0d340e08cb4dd45f9c3685d
    templateId: f1b714345be64a0bb6efc421cc19ef13
    smsSignId: 2e65b1bb3d054466b82f0c9d125465e2

ruoyi:
  rmq:
    producer:
      nameSrv: 1.13.154.224:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2
    consumer:
      nameSrv: 1.13.154.224:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

# 数据加密
mybatis-encryptor:
  # 是否开启加密
  enable: false
  # 默认加密算法
  algorithm: BASE64
  # 编码方式 BASE64/HEX。默认BASE64
  encode: BASE64
  # 安全秘钥 对称算法的秘钥 如：AES，SM4
  password:
  # 公私钥 非对称算法的公私钥 如：SM2，RSA
  publicKey:
  privateKey: